### ISSUE TITLE
Nodejs: Session closed when running defiant.search a second time

### ISSUE THREAD

**Issue by mapi33** [hbi99/defiant.js#121]
I've got the following function in nodejs (for test purpose)

const defiant =  require('defiant.js');

const json = {"coord":{"lon":-0.13,"lat":51.51},"weather":[{"id":300,"main":"Drizzle","description":"light intensity drizzle","icon":"09d"}]}

const evaluateJSON = async (jsonStr, xPath) => {

    let res = await defiant.search(JSON.parse(jsonStr), xPath)
    console.log("res", res);

    let res2 = await defiant.search(JSON.parse(jsonStr), xPath)      // ==>throws error
    console.log("res2", res2);

    return res
}

evaluateJSON(JSON.stringify(json), "//*")
the first search works well!
the second search triggers an error

node:12845) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/var/www/api/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/www/api/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/var/www/api/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/var/www/api/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/var/www/api/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/var/www/api/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/api/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/var/www/api/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/var/www/api/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.search (/var/www/api/node_modules/defiant.js/index.js:67:37)
    at evaluateJSON (/var/www/api/src/tests/defiant.js:10:30)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
I run defiant.js v 2.2.6
Node v11.10.0

**Comment by hbi99** [comment]
Hi @mapi33,
You can choose to keep defiant "persist", by adding `true` as third argument...like so:

```js
let data = JSON.parse(jsonStr);
let res = await defiant.search(data, xPath, true)
console.log("res", res);

let res2 = await defiant.search(data, xPath, true)      // ==>throws error
console.log("res2", res2);
```

The reason for the "auto-kill", is to clear memory that puppeteer uses. Defiant assumes that you are using it once and after that cleans up...try to at least :-)
